name: ecomerce_test
description: "A test project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  toastification: ^2.2.0
  go_router: ^14.2.7
  flutter_screenutil: ^5.9.3
  dropdown_button2: ^2.3.9
  flutter_hooks: ^0.20.5
  country_picker: ^2.0.26
  dio: ^5.7.0
  hive: ^2.2.3
  get: ^5.0.0-release-candidate-9.2
  connectivity_plus: ^6.0.5
  cached_network_image: ^3.4.1
  rating_bar_flutter: ^1.0.2
  hive_flutter: ^1.1.0
  lottie: ^3.1.2

  collection: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lottie/
